import {
  love,
  paper,
  lucky,
  lightning,
  number2,
  cool,
  sakura,
  clova,
  champagne,
  gift,
  celebration,
  newyear,
  slotmachine,
  runningwoman,
  health,
  health2,
  chick,
  ear,
  oksing,
  good,
  graduate,
  wedding,
  baby,
  ring,
  wind,
  power,
  maxscore,
  money,
  soon,
  happy1,
  happy2,
  devil,
  clap,
  nosmoking,
  moneyface,
  purpledevil,
  gini,
  kite,
  couple,
  qustion,
} from '../../img';

import {
  clock,
  sun,
  pen,
  loveRight,
  luckyRight,
  lightningRight,
  star,
  brige,
  leaf,
  newyearRight,
  graduateRight,
  slotmachineRight,
  melody,
  trumpet,
  race,
  runningman,
  whiterabbit,
  rabbit,
  hand,
  thumb,
  girl,
  catwoman,
  weddingRight,
  babyRight,
  loveRiibon,
  strong,
  starRight,
  moneyRight,
  moneyRight2,
  book,
  smail,
  sunglasses,
  wink,
  omg,
  clapRight,
  nosmokingRight,
  babyRight2,
  redSign,
  goal,
  happyRight,
  circus,
  kiteRight,
  mars,
  number3,
  x,
  qustionRight,
} from '../../img';
export const imgFileLeft = [
  qustion,
  champagne,
  lightning,
  health2,
  baby,
  power,
  good,
  nosmoking,
  money,
  moneyface,
  slotmachine,
  newyear,
  oksing,
  lucky,
  love,
  ring,
  gift,
  wedding,
  maxscore,
  runningwoman,
  soon,
  graduate,
  sakura,
  clova,
  happy1,
  happy2,
  celebration,
  purpledevil,
  ear,
  gini,
  clap,
  wind,
  paper,
  //여기 까지 씀
  number2,
  cool,
  health,
  chick,
  devil,
  kite,
  couple,
];
export const imgFileRight = [
  qustionRight,

  x,
  rabbit,
  strong,
  babyRight2,
  wink,
  luckyRight,
  sunglasses,
  nosmokingRight,
  lightningRight,
  circus,
  moneyRight2,
  slotmachineRight,
  trumpet,
  moneyRight,
  clapRight,
  thumb,
  pen,
  redSign,
  loveRight,
  clock,
  weddingRight,
  catwoman,
  smail,
  loveRiibon,
  book,
  sun,
  runningman,
  graduateRight,
  race,
  goal,
  omg,
  newyearRight,
  star,
  melody,
  mars,
  kiteRight,
  number3,
  babyRight,
  starRight,
  hand,
  brige,
  leaf,
  whiterabbit,
  //여기까지 씀

  girl,
  happyRight,
];

export const slot = [
  [champagne, x, '건강운'],
  [lightning, rabbit, '건강운'],
  [health2, strong, '건강운'],
  [baby, babyRight2, '건강운'],
  [power, wink, '건강운'],
  [thumb, luckyRight, '건강운'],
  [power, sunglasses, '건강운'],
  [nosmoking, nosmokingRight, '건강운'],
  [money, lightningRight, '금전운'],
  [money, circus, '금전운'],
  [moneyface, money, '금전운'],
  //10
  [slotmachine, slotmachineRight, '금전운'], //11
  [newyear, trumpet, '금전운'],
  [paper, pen, '금전운'],
  [happy2, redSign, '애정운'],
  [champagne, x, '건강운'],
  [love, clock, '애정운'],
  [ring, weddingRight, '애정운'],
  [love, catwoman, '애정운'],
  [love, happyRight, '애정운'],
  [gift, loveRight, '애정운'],
  //20
  [wedding, book, '애정운'], //21
  [maxscore, sun, '애정운'],
  [runningwoman, runningman, '직장운'],
  [graduate, graduateRight, '학업운'],
  [runningwoman, race, '학업운'],
  [runningwoman, race, '직장운'],
  [sakura, goal, '학업운'],
  [sakura, goal, '직장운'],
  [clova, omg, '학업운'],
  [clova, omg, '직장운'], //30
  [happy2, runningman, '학업운'], //31
  [happy2, runningman, '직장운'],
  [happy1, happyRight, '학업운'],
  [happy1, happyRight, '직장운'],
  [celebration, newyearRight, '학업운'],
  [celebration, newyearRight, '직장운'],
  [purpledevil, starRight, '학업운'],
  [purpledevil, starRight, '직장운'],
  [ear, melody, '학업운'],
  [ear, melody, '직장운'],
  [gini, mars, '행운'],
  [gini, girl, '행운'],
  [kite, kiteRight, '행운'],
  [number2, number3, '행운'],
  [chick, babyRight, '행운'],
  [gini, starRight, '행운'],
  [clap, clapRight, '행운'],
  [sakura, brige, '행운'],
  [wind, clapRight, '행운'],
  [soon, whiterabbit, '행운'],
];

export const data = [
  ['money', '💰', '재물운'],
  ['health', '💪', '건강운'],
  ['love', '💗', '애정운'],
  ['study', '📚', '학업운'],
  ['lucky', '🎁 ', '행운'],
  ['work', '👔', '직장운'],
];
