import {
  love,
  paper,
  lucky,
  lightning,
  number2,
  cool,
  sakura,
  clova,
  champagne,
  gift,
  celebration,
  newyear,
  slotmachine,
  runningwoman,
  health,
  health2,
  chick,
  ear,
  oksing,
  good,
  graduate,
  wedding,
  baby,
  ring,
  wind,
  power,
  maxscore,
  money,
  soon,
  happy1,
  happy2,
  devil,
  clap,
  nosmoking,
  moneyface,
  purpledevil,
  gini,
  kite,
  couple,
  qustion,
} from '../../img';

import {
  clock,
  sun,
  pen,
  loveRight,
  luckyRight,
  lightningRight,
  star,
  brige,
  leaf,
  newyearRight,
  graduateRight,
  slotmachineRight,
  melody,
  trumpet,
  race,
  runningman,
  whiterabbit,
  rabbit,
  hand,
  thumb,
  girl,
  catwoman,
  weddingRight,
  babyRight,
  loveRiibon,
  strong,
  starRight,
  moneyRight,
  moneyRight2,
  book,
  smail,
  sunglasses,
  wink,
  omg,
  clapRight,
  nosmokingRight,
  babyRight2,
  redSign,
  goal,
  happyRight,
  circus,
  kiteRight,
  mars,
  number3,
  x,
  qustionRight,
} from '../../img';
import {
  healthyCategory,
  loveCategory,
  luckyCategory,
  moneyCategory,
  studyCategory,
  workCategory,
} from '../../img';
export const imgFileLeft = [
  qustion,
  champagne,
  lightning,
  health2,
  baby,
  power,
  good,
  nosmoking,
  money,
  moneyface,
  slotmachine,
  newyear,
  oksing,
  lucky,
  love,
  ring,
  gift,
  wedding,
  maxscore,
  runningwoman,
  soon,
  graduate,
  sakura,
  clova,
  happy1,
  happy2,
  celebration,
  purpledevil,
  ear,
  gini,
  clap,
  wind,
  paper,
  //여기 까지 씀
  number2,
  cool,
  health,
  chick,
  devil,
  kite,
  couple,
];
export const imgFileRight = [
  qustionRight,

  x,
  rabbit,
  strong,
  babyRight2,
  wink,
  luckyRight,
  sunglasses,
  nosmokingRight,
  lightningRight,
  circus,
  moneyRight2,
  slotmachineRight,
  trumpet,
  moneyRight,
  clapRight,
  thumb,
  pen,
  redSign,
  loveRight,
  clock,
  weddingRight,
  catwoman,
  smail,
  loveRiibon,
  book,
  sun,
  runningman,
  graduateRight,
  race,
  goal,
  omg,
  newyearRight,
  star,
  melody,
  mars,
  kiteRight,
  number3,
  babyRight,
  starRight,
  hand,
  brige,
  leaf,
  whiterabbit,
  //여기까지 씀
  girl,
  happyRight,
];

export const slot = [
  [champagne, x, healthyCategory, '건강운', 'AlcoholFree', '마신 게 하나도 없는데'],
  [
    lightning,
    rabbit,
    healthyCategory,
    '건강운',
    'Energy',
    'MY 에너지 나는 너의 에너지 One Two Three E N E R G Y',
  ],
  [health2, strong, healthyCategory, '건강운', 'Gunny', '지금부터 나와같이 어서빨리 운동하자'],
  [
    baby,
    babyRight2,
    healthyCategory,
    '건강운',
    'ForeverYoung',
    '후회 없는 젊음이 타오르게 Forever young',
  ],
  [
    power,
    wink,
    healthyCategory,
    '건강운',
    'antifragile',
    "I'm antifragile antifragile Anti ti ti ti fragile fragile",
  ],
  [
    thumb,
    luckyRight,
    healthyCategory,
    '건강운',
    'Allgood',
    "Everything, everything's fine 너대로 충분한 걸",
  ],
  [
    power,
    sunglasses,
    healthyCategory,
    '건강운',
    'Soran',
    '넌 모를 거야 내가 얼마나 준비된 어깨를 가졌는지',
  ],
  [
    nosmoking,
    nosmokingRight,
    healthyCategory,
    '건강운',
    'NoSmoking',
    '그대 담배를 끊어봐요 (담배 연기 싫어) 건강에도 안 좋은 걸 왜 자꾸 피우시나',
  ],
  [
    money,
    lightningRight,
    moneyCategory,
    '재물운',
    'JackPot',
    '지갑에도 가득. 통장에도 가득 돈벼락 쏟아진다',
  ],
  [money, circus, moneyCategory, '재물운', 'Lotto', 'I just hit the lotto'],
  [
    moneyface,
    money,
    moneyCategory,
    '재물운',
    'Money',
    "Money it's a hit I'm in the hi-fidelity first class traveling set",
  ],
  [
    slotmachine,
    slotmachineRight,
    moneyCategory,
    '재물운',
    'BlockB',
    '야호 터졌다 Ja Ja Ja Jackpot',
  ],
  [
    newyear,
    trumpet,
    moneyCategory,
    '재물운',
    'Fiesta',
    '축제는 절정인 걸 끝나지 않을 이건 Climax  나의 모든 순간이 아름답고 눈부셔',
  ],
  [
    oksing,
    moneyRight,
    moneyCategory,
    '재물운',
    'Coin',
    '승리를 손에 꽉 잡아 말아 쥐어 Worth more than jewels',
  ],
  [
    lucky,
    clapRight,
    moneyCategory,
    '재물운',
    'DreamsComeTrue',
    'All your dreams come true 널 믿어 dreams come true',
  ],

  //10
  [paper, pen, moneyCategory, '재물운', 'Sign', '끝엔 해피엔딩일 거야 나도 해냈잖아 취뽀'],
  [paper, pen, workCategory, '직장운', 'Sign', '끝엔 해피엔딩일 거야 나도 해냈잖아 취뽀'],

  [happy2, redSign, loveCategory, '애정운', 'Happiness', '점점 더 좋은걸 난 나라서 행복해'],
  [
    love,
    clock,
    loveCategory,
    '애정운',
    'In LovesTime',
    "In love's time, all you'll ever need In the life you lead will be guaranteed",
  ],
  [
    ring,
    weddingRight,
    loveCategory,
    '애정운',
    'Marry',
    '아프지 마요 언제나 웃어요 약속할게요 그대만을 사랑해요 My Lover Lover 나와 결혼해줘요',
  ],
  [
    love,
    catwoman,
    loveCategory,
    '애정운',
    'ConfessionOfAFriend',
    '친구로 친구로 지내야 한단 이유로 하지만 이제는 고백할께. 너를 사랑해',
  ],
  [
    love,
    happyRight,
    loveCategory,
    '애정운',
    'Realslow',
    '사랑은 맛있어 달빛 젖은 햇살 머금은 세상의 선물',
  ],
  [gift, loveRight, loveCategory, '애정운', 'Gift', '항상 평범했던 일상도 특별해지는 이 순간'],
  //20
  [
    wedding,
    book,
    loveCategory,
    '애정운',
    'WeddingDiary',
    '이렇게 우리 함께 늙자 오늘자 우리의 신혼일기',
  ], //21
  [maxscore, sun, loveCategory, '애정운', 'Eternity', '우리 같이 영원을 꿈꾸자'],
  [
    runningwoman,
    runningman,
    workCategory,
    '직장운',
    '2NE1',
    '내가 봐도 내가 좀 끝내주잖아 네가 나라도 이 몸이 부럽잖아 ',
  ],
  [
    graduate,
    graduateRight,
    studyCategory,
    '학업운',
    'Graduate',
    '함께했던 시간은 이젠 추억으로 남기고 서로 가야 할 길 찾아서 떠나야 해요',
  ],
  [
    runningwoman,
    race,
    studyCategory,
    '학업운',
    'Gaho',
    '새로운 시작은 늘 설레게 하지 모든 걸 이겨낼 것처럼',
  ],
  [
    runningwoman,
    race,
    workCategory,
    '직장운',
    'Gaho',
    '새로운 시작은 늘 설레게 하지 모든 걸 이겨낼 것처럼',
  ],
  [
    sakura,
    goal,
    studyCategory,
    '학업운',
    'FlowerRoad',
    '젊고 아름다운 당신의 계절 여길 봐 예쁘게 피었으니까',
  ],
  [
    sakura,
    goal,
    workCategory,
    '직장운',
    'FlowerRoad',
    '젊고 아름다운 당신의 계절 여길 봐 예쁘게 피었으니까',
  ],
  [
    clova,
    omg,
    studyCategory,
    '학업운',
    'JRabbit',
    '웬만하면 크게 웃고 다시 시작해봐 오늘은 좋은일이 있을거야',
  ],
  [
    clova,
    omg,
    workCategory,
    '직장운',
    'JRabbit',
    '웬만하면 크게 웃고 다시 시작해봐 오늘은 좋은일이 있을거야',
  ], //30
  [happy2, runningman, studyCategory, '학업운', 'Start', '이렇게 나는 떠나네 더 넓은 세상으로'], //31
  [happy2, runningman, workCategory, '직장운', 'Start', '이렇게 나는 떠나네 더 넓은 세상으로'],
  [happy1, happyRight, studyCategory, '학업운', 'DaySix', '반드시 웃는다 웃는다'],
  [happy1, happyRight, workCategory, '직장운', 'DaySix', '반드시 웃는다 웃는다'],
  [
    celebration,
    newyearRight,
    studyCategory,
    '학업운',
    'Fanfare',
    '꿈꾸던 시간이 마치 오늘인 것만 같아 맘이 두근거리다 심장이 쿵 떨어져',
  ],
  [
    celebration,
    newyearRight,
    workCategory,
    '직장운',
    'Fanfare',
    '꿈꾸던 시간이 마치 오늘인 것만 같아 맘이 두근거리다 심장이 쿵 떨어져',
  ],
  [
    purpledevil,
    starRight,
    studyCategory,
    '학업운',
    'SuperStar',
    '괜찮아 잘 될거야 너에겐 눈부신 미래가 있어 후회없이만 산다면 그것이 Super Star',
  ],
  [
    purpledevil,
    starRight,
    workCategory,
    '직장운',
    'SuperStar',
    '괜찮아 잘 될거야 너에겐 눈부신 미래가 있어 후회없이만 산다면 그것이 Super Star',
  ],
  [
    ear,
    melody,
    studyCategory,
    '학업운',
    'Jobin',
    '무엇이든 상상하기만하면 이루어진다 로또는 비교도 안될 성공이 ',
  ],
  [
    ear,
    melody,
    workCategory,
    '직장운',
    'Jobin',
    '무엇이든 상상하기만하면 이루어진다 로또는 비교도 안될 성공이 ',
  ],
  [gini, mars, luckyCategory, '행운', 'AsYouWish', '이루리 이루리 La 모두 다 이뤄질 거야'],
  [
    gini,
    girl,
    luckyCategory,
    '행운',
    'IOI',
    '시간은 충분해 조급해하지마 Trust yourself 너 포기하지마',
  ],
  [
    kite,
    kiteRight,
    luckyCategory,
    '행운',
    'NewYear',
    '새해 복만으로도 돼 절대 잘 하지 마 (돼) 열심히 하지 마 (돼)',
  ],
  [
    number2,
    number3,
    luckyCategory,
    '행운',
    'IU',
    '얄미운 스물셋 .아직 한참 멀었다 얘 덜 자란 척해도  대충 속아줘요 ',
  ],
  [chick, babyRight, luckyCategory, '행운', 'Fly', '새롭게 펼쳐봐 또 날아봐 이제'],
  [gini, starRight, luckyCategory, '행운', 'Aespa', '나를 지켜줄 거야 아껴왔던 작은 사랑도'],
  [
    clap,
    clapRight,
    luckyCategory,
    '행운',
    'Hello',
    '외로운 날들이여 모두 다 안녕 내 마음속의 눈물들도 이제는 안녕 Oh',
  ],
  [sakura, brige, luckyCategory, '행운', 'Spring', '꽃 피울 때까지 그곳에 좀 더 머물러줘'],
  [wind, clapRight, luckyCategory, '행운'],
  [soon, whiterabbit, luckyCategory, '행운'],
];
export const song = [
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
];
export const category = [
  qustionRight,
  healthyCategory,
  loveCategory,
  luckyCategory,
  moneyCategory,
  studyCategory,
  workCategory,
];
export const data = [
  ['money', '💰', '재물운'],
  ['health', '💪', '건강운'],
  ['love', '💗', '애정운'],
  ['study', '📚', '학업운'],
  ['lucky', '🎁 ', '행운'],
  ['work', '👔', '직장운'],
];
